baseURL = "https://hao.bioitee.com"
languageCode = "zh-CN"
title = "生信网址导航 | BioWebStack"
theme = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
publishDir = "docs"

[params]
    author        = "shenweiyan"
    description   = "生信网址导航 | Bio IT 爱好者"
    siteurl       = "./"
    upload        = "https://www.yuque.com/forms/share/1a1fee15-f7a9-4ee6-9dd4-b0ba9fef1871"
    about         = "https://shumlab.com/cookbook/biowebstack"	              # 左侧导航栏的"关于我们"页面(./about)
    repository    = "https://github.com/shenweiyan/WebStack-Hugo"   	
    enablePreLoad = true	                                              # 网站完全打开前预加载的动画
    textPreLoad   = "生信网址导航"	                                      # 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false                                                     # 默认展开左侧边导航栏
    logosPath     = "https://static.bioitee.com/webstack/logos"	              # 网站每个导航地址logo存放地址
    defaultLogo   = "https://static.bioitee.com/webstack/logos/default.webp"  # logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    baiduhmid     = '6eb87932f29f7e3a58bf1a37a1696810'                        # 百度统计 hm.src 的 ID

[markup.goldmark.renderer]
    unsafe = true

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "https://static.bioitee.com/webstack/sites/bi-favicon.png"
    searchImageL      = "https://shenweiyan.github.io/CustomAssets/NavHUB/sites/bg-dna.jpg"		#搜索部分浅色背景图
    searchImageD      = "https://shenweiyan.github.io/CustomAssets/NavHUB/sites/bg-dna.jpg"		#搜索部分深色背景图
    logoExpandLight   = "https://static.bioitee.com/webstack/sites/biwebstack-l.png"
    logoExpandDark    = "https://static.bioitee.com/webstack/sites/biwebstack-d.png"
    logoCollapseLight = "https://static.bioitee.com/webstack/sites/bi-logo.png"
    logoCollapseDark  = "https://static.bioitee.com/webstack/sites/bi-logo.png"

[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：<a href="http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=shumlab@foxmail.com" target="_blank">shumlab@foxmail.com</a> <br/>&copy; 2021 - {year} By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo) | [Bio IT 爱好者](https://www.bioitee.com/) | [粤ICP备16023717号](http://beian.miit.gov.cn/)<br/>Powered by [GitHub Pages](https://github.com/bioitee/BioWebStack) <br/><a href="https://tongji.baidu.com/" target="_blank"><img border="0" src="https://tongji.baidu.com/sc-web/image/icon/31.gif" alt="百度统计" title="百度统计"></a>'
